---
# docs:
#   - https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
#   - https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgm-velero
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mgm
  destination:
    name: ''
    namespace: mgm
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  source:
    path: ''
    repoURL: 'https://vmware-tanzu.github.io/helm-charts'
    targetRevision: 5.4.1
    chart: velero
    helm:
      values: |
        # ref: https://velero.io/plugins/
        initContainers:
          - name: velero-plugin-for-csi
            image: velero/velero-plugin-for-csi:v0.7.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.9.1
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins

        configuration:
          extraEnvVars:
            TZ: Asia/Tokyo
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: velero
              accessMode: ReadWrite
              config:
                region: minio-default
                s3ForcePathStyle: "true"
                s3Url: http://mysticstorage.local:9000
                publicUrl: http://mysticstorage.local:9000
                insecureSkipTLSVerify: true
          volumeSnapshotLocation:
            - name: default
              provider: aws
              config:
                region: minio-default
                s3ForcePathStyle: "true"
                s3Url: http://mysticstorage.local:9000
                publicUrl: http://mysticstorage.local:9000
                insecureSkipTLSVerify: true
          features: EnableCSI

        credentials:
          secretContents:
            cloud: |
              [default]
              aws_access_key_id=tnBwNmT7I4UZQaZR0EDv
              aws_secret_access_key=JTYD9Qaz0h72greLoHOaWY0FC8TOR7WvC2Au6pCL

        snapshotsEnabled: false

        deployNodeAgent: true
